### ISSUE TITLE
Attendance Points

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#100]
Can the attendance points be displayed when clicking on the attendance tab while in the review process as they are when viewing a profile? Please!!

**Comment by kc9eye** [comment]
Maybe

P.Lane
KC9EYE
________________________________
From: tea1677 ***@***.***>
Sent: Wednesday, March 17, 2021 8:10:52 AM
To: kc9eye/UData ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kc9eye/UData] Attendance Points (#100)


Can the attendance points be displayed when clicking on the attendance tab while in the review process as they are when viewing a profile? Please!!
