### ISSUE TITLE
Inventory Count Scrolling

### ISSUE THREAD

**Issue by adambaldauf** [kc9eye/UData#102]
When entering inventory counts for WIP and counted items, hitting add refreshes the page and scrolls the page back to the top.  Is there a way to stop the page from scrolling, after hitting the add button?

**Comment by kc9eye** [comment]
Yes

P.Lane
KC9EYE
________________________________
From: adambaldauf ***@***.***>
Sent: Thursday, April 1, 2021 8:03:38 AM
To: kc9eye/UData ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kc9eye/UData] Inventory Count Scrolling (#102)


When entering inventory counts for WIP and counted items, hitting add refreshes the page and scrolls the page back to the top. Is there a way to stop the page from scrolling, after hitting the add button?
