### ISSUE TITLE
Product Search Issue

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#103]
When searching for AT products it shows no products even though there is an AT product. 
Please Help!!!!!!!

**Comment by kc9eye** [comment]
‘AT’ is not a search term and is disregarded by all search engines currently as a common conjunction. Your product is visible on the active products page. I would suggest adding the term “buildsheet” to your search, as in “AT buildsheet”.

P.Lane
KC9EYE
________________________________
From: tea1677 ***@***.***>
Sent: Tuesday, May 4, 2021 10:46:39 AM
To: kc9eye/UData ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kc9eye/UData] Product Search Issue (#103)


When searching for AT products it shows no products even though there is an AT product.
Please Help!!!!!!!
