### ISSUE TITLE
Training feature request

### ISSUE THREAD

**Issue by adambaldauf** [kc9eye/UData#2]
Within the human resources module, while adding a skill to an employee.  Would it be possible to have a multiple selectable list to replace the dropdown list that is currently being used?  The dropdown list is becoming cumbersome due to multiple different products and stations we have within our process.

**Comment by kc9eye** [comment]
Sure

**Comment by kc9eye** [comment]
Fixed in da06bcf78bcd75a68edeb58149d8fe09e6bf1d1d
