### ISSUE TITLE
New User Account multiple emails

### ISSUE THREAD

**Issue by adambaldauf** [kc9eye/UData#38]
**Describe the bug**
When a new user account is created, 3 identical emails are sent.  All with the following info.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44575846/47652534-3227b900-db54-11e8-9b6f-ea092cbdd4d6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kc9eye** [comment]
This should be fixed in https://github.com/kc9eye/UData/commit/95998476e98bbc0df0b1336e470a3e47ac5508e2 . Let me know if it does not.

**Comment by kc9eye** [comment]
This should be fixed now. It was the way in which PHPMailer handles it's data, as an instance of the mailer does not unset it's data between sends.
Should be fixed in https://github.com/kc9eye/UData/commit/a619275fb6583239aa6d2b3eabe6491ce06af437
