### ISSUE TITLE
Work Cells View additional column

### ISSUE THREAD

**Issue by adambaldauf** [kc9eye/UData#46]
On the work cells page, an additional column showing the current quality statistics would aid in showing troubled stations more readily.

**Comment by kc9eye** [comment]
I agree, and this will be implemented at the 
`/cells/main?action=list&prokey=_valid_master_product_key_`
API and not the `/cells/main?cell_search=_search_terms_`
API. As @adambaldauf demonstrated directly. This will keep unauthorized users from accessing that data.
