### ISSUE TITLE
Using the back arrow

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#48]
After entering material into a work cell and then pressing the back arrow to go back to the product view I am getting an error message. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kc9eye** [comment]
Going to need more for this. Do you get a blue screen error, what is the blue screen error ID?

Paul W. Lane
KC9EYE
Chicago Assembly Division

________________________________

**Comment by tea1677** [comment]
Please add an return to Product View button.

**Comment by kc9eye** [comment]
Will implement ASAP.

Paul W. Lane
KC9EYE
Chicago Assembly Division

________________________________
