### ISSUE TITLE
ID: ERR_5c64374ce9c0e

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#49]
ID: ERR_5c64374ce9c0e

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kc9eye** [comment]
Not sure what happened there, log points to an 'Undefined offset:0'. It appears that the application could not find the work cell data at that point. This may have been due to the database hanging on to another transaction at that moment.
