### ISSUE TITLE
Time out error on injury report

### ISSUE THREAD

**Issue by adambaldauf** [kc9eye/UData#5]
When attempting to submit an injury report, after "pressing" the submit button, the screen flashes multiple times approximately 3 seconds apart before finally landing on the timeout error below.

![image](https://github.com/kc9eye/UData/assets/44575846/b9dbd508-6f56-4026-a394-f9ad189a8cbd)

**Comment by kc9eye** [comment]
Fixed in backend. Updated database tables for search indexing
