### ISSUE TITLE
Attendance Date Range

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#57]
Add a date range for attendance entry.

**Comment by kc9eye** [comment]
I can implement this, however the actual entry will be multiple of the original, only with differing dates that include all the dates in the range. This will keep the data consistent, with each date having an entry for calculations, and filtering.

Paul Lane
Chicago Assembly Division

________________________________

**Comment by tea1677** [comment]
English please!!!

Todd Anderson
Production Manager (447-000)
Chicago Assembly Division
447-108 \ 219-322-4757

________________________________
