### ISSUE TITLE
OOPS

### ISSUE THREAD

**Issue by tea1677** [kc9eye/UData#97]
When deleting an checkpoint entry it does not go away but does create a blank space. Please fix.

**Comment by kc9eye** [comment]
Sure

**Comment by kc9eye** [comment]
I can not confirm the complaint. I have added both; with work cell and without work cell, test entries on the alpha, testing, and main line builds can not reproduce the bug. The blank entries were deleted through the regular interface. I am attributing this to hair ball, without further information I am closing this report.
